version: "3"

services:
  db:
    image: mysql:8
    container_name: mysql8
    volumes:
     - fullstackdata:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=${DB_DATABASE}
     - MYSQL_ROOT_USER=${DB_USERNAME}
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
     - 3306:3306

volumes:
  fullstackdata:
