# Generated by Django 2.2.9 on 2021-07-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('source_port', models.FloatField(blank=True)),
                ('destination_ip', models.GenericIPAddressField()),
                ('destination_port', models.FloatField(blank=True)),
                ('dns_record', models.CharField(max_length=500)),
                ('datetime_record', models.DateTimeField(blank=True)),
            ],
        ),
    ]
